### ISSUE TITLE
Suggestion: Make 'choice_option' and 'choice_argument' accept default values on the questionary!

### ISSUE THREAD

**Issue by Dominiquini** [markusgrotz/click-prompt#1]

**Comment by markusgrotz** [comment]
Thank you! That seems like a really good suggestion to me. I have started implementing that. Will merge it soon!

**Comment by Dominiquini** [comment]
> Thank you! That seems like a really good suggestion to me. I have started implementing that. Will merge it soon!

I was testing here locally and also submitted a Pull-Request: https://github.com/markusgrotz/click-prompt/pull/3

My version show the default value pre-selected! 

Thanks.

**Comment by markusgrotz** [comment]
Thank you again for the suggestion and the commits! I appreciate your help here!

**Comment by Dominiquini** [comment]
> Thank you again for the suggestion and the commits! I appreciate your help here!

Just one last thing! I think the class 'FilePathParameter' should accept a empty string ("") as default value! My app was trying to define it that way (the parameter could be empty), but this lib is changing to "~"!

Thanks.

**Comment by markusgrotz** [comment]
Thank you! That's a good point. I just changed it.

**Comment by Dominiquini** [comment]
> Thank you! That's a good point. I just changed it.

Thanks.

When you planning to update on PyPi?

**Comment by markusgrotz** [comment]
Done. Package is now uploaded to pypi.
